[package]
name = "mousql_tcp_tester"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.0" , features = ["full"]}
anyhow = "1.0.98"
mousqlite_types = { path = "../mousqlite_types"}
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"